branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
cran: https://cran.rstudio.com

warnings_are_errors: false
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - bioc-release

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libmagick++-dev
  - sudo apt-get -y install librsvg2-dev
  - sudo apt-get -y install libwebp-dev
  - sudo apt-get -y install libpoppler-cpp-dev
  - sudo apt-get -y install libtesseract-dev
  - sudo apt-get -y install libleptonica-dev
  - sudo apt-get -y install tesseract-ocr-eng
  - sudo apt-get -y install libfftw3-dev
  - sudo apt-get -y install cargo

r_packages:
  - gert
  - devtools
  - covr
  - BiocManager
  - elasticnet
  - sparsepca
  - magick
  - Matrix
  - matrixStats
  - coop
  - RSpectra

r_github_packages:
  - r-lib/sessioninfo
  - r-lib/covr
  - LTLA/ScaledMatrix

bioc_packages:
  - BiocStyle
  - BiocCheck
  - BiocGenerics
  - BiocParallel
  - S4Vectors
  - splatter
  - SingleCellExperiment
  - Rhdf5lib
  - HDF5Array
  - DelayedArray
  - DelayedMatrixStats
  - sparseMatrixStats
  - MatrixGenerics

after_success:
  ## coverage
  - travis_wait 60 Rscript -e "covr::codecov()"
  - R CMD BiocCheck .

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
